parameters:
  prometheus:
    server:
      target:
        dns:
          enabled: true
          endpoint:
            - name: 'alertmanager'
              domain:
              - 'tasks.monitoring_alertmanager'
              type: A
              port: ${prometheus:alertmanager:bind:port}
