parameters:
  prometheus:
    server:
      target:
        dns:
          enabled: true
          endpoint:
            - name: 'prometheus'
              domain:
              - 'tasks.monitoring_server'
              type: A
              port: ${prometheus:server:bind:port}
