parameters:
  prometheus:
    server:
      target:
        dns:
          enabled: true
          endpoint:
            - name: 'pushgateway'
              domain:
              - 'tasks.monitoring_pushgateway'
              type: A
              port: ${prometheus:pushgateway:bind:port}