parameters:
  prometheus:
    server:
      target:
        dns:
          enabled: true
          endpoint:
            - name: 'remote_agent'
              domain:
              - 'tasks.monitoring_remote_agent'
              type: A
              port: ${telegraf:remote_agent:output:prometheus_client:bind:port}
