parameters:
  prometheus:
    server:
      target:
        dns:
          enabled: true
          endpoint:
            - name: 'remote_storage_adapter'
              domain:
              - 'tasks.monitoring_remote_storage_adapter'
              type: A
              port: ${prometheus:remote_storage_adapter:bind:port}
