applications:
- memcached
classes:
- service.memcached.support
parameters:
  memcached:
    server:
      enabled: true
      maxconn: 8192
      bind:
        address: 127.0.0.1
        port: 11211
        protocol: tcp
