parameters:
  _param:
    alerta_environment_label: ${_param:cluster_name}
  prometheus:
    server:
      config:
        alert:
          labels_add:
            environment: ${_param:alerta_environment_label}
        alert_relabel_configs:
          - replacement: "aggregated"
            source_labels: "instance"
            target_label: "instance"
          - source_labels: "host"
            target_label: "instance"
            regex: "(.+)"
          - source_labels: "job"
            target_label: "instance"
            regex: "(.+)"
          - source_labels: ["host", "job"]
            target_label: "instance"
            regex: "(.+;.+)"
          - source_labels: ["hostname", "job"]
            target_label: "instance"
            regex: "(.+;.+)"
