parameters:
  docker:
    client:
      stack:
        monitoring:
          service:
            server:
              deploy:
                mode: global
              environment:
                PROMETHEUS_USE_STATIC_DATADIR: "true"
