applications:
- grafana
classes:
- grafana.client
- grafana.client.datasource.influxdb
parameters:
  _param:
    grafana_address: ${_param:stacklight_monitor_address}
    grafana_influxdb_address: ${_param:grafana_influxdb_host}
    grafana_influxdb_database: lma
    grafana_influxdb_ds_name: lma
    grafana_influxdb_password: ${_param:influxdb_stacklight_password}
    grafana_influxdb_port: ${_param:influxdb_port}
    grafana_influxdb_user: lma
  grafana:
    client:
      base_templates:
        cluster_status_singlestat:
          colorBackground: true
          colors:
          - rgba(71, 212, 59, 0.4)
          - rgba(245, 150, 40, 0.73)
          - rgba(225, 40, 40, 0.59)
          editable: false
          interval: '> 60s'
          postfixFontSize: 50%
          prefixFontSize: 50%
          span: 2
          sparkline:
            fillColor: rgba(31, 118, 189, 0.18)
            full: false
            lineColor: rgb(31, 120, 193)
            show: false
          thresholds: 1,3
          type: singlestat
          valueFontSize: 50%
          valueMaps:
          - op: =
            text: no data
            value: "null"
          - op: =
            text: OKAY
            value: "0"
          - op: =
            text: WARN
            value: "1"
          - op: =
            text: UNKW
            value: "2"
          - op: =
            text: CRIT
            value: "3"
          - op: =
            text: DOWN
            value: "4"
          valueName: current
        main_dashboard:
          editable: true
          hideControls: false
          templating:
            enable: true
            list:
            - allFormat: regex values
              hide: 0
              includeAll: false
              multi: false
              name: environment
              options: []
              query: show tag values from cpu_idle with key = environment_label
              refresh: 1
              refresh_on_load: true
              regex: ""
              sort: 0
              type: query
          title: Main
        prometheus_cluster_status:
          colorBackground: true
          colors:
          - rgba(225, 40, 40, 0.59)
          - rgba(245, 150, 40, 0.73)
          - rgba(71, 212, 59, 0.4)
          editable: false
          interval: '> 60s'
          mappingType: 2
          postfixFontSize: 50%
          prefixFontSize: 50%
          rangeMaps:
          - from: "null"
            text: no data
            to: "null"
          - from: "0"
            text: DOWN
            to: "0"
          - from: "0.01"
            text: CRIT
            to: "0.5"
          - from: "0.51"
            text: WARN
            to: "0.99"
          - from: "1"
            text: UP
            to: "1"
          - from: "2"
            text: UNKW
            to: "2"
          span: 2
          sparkline:
            fillColor: rgba(31, 118, 189, 0.18)
            full: false
            lineColor: rgb(31, 120, 193)
            show: false
          thresholds: 0.01,1
          type: singlestat
          valueFontSize: 50%
          valueName: current
        prometheus_main_dashboard:
          editable: true
          hideControls: false
          title: Main
        service_level_dashboard:
          editable: true
          hideControls: false
          templating:
            enable: true
            list:
            - allFormat: regex values
              hide: 0
              includeAll: false
              multi: false
              name: environment
              options: []
              query: show tag values from cpu_idle with key = environment_label
              refresh: 1
              refresh_on_load: true
              regex: ""
              sort: 0
              type: query
          title: Service Level Indicators
        service_level_piechart:
          aliasColors:
            Degraded or Unknown: '#EAB839'
            Down: '#890F02'
            Error: '#890F02'
            Fatal: '#890F02'
            Healthy: '#7EB26D'
            Okay: '#7EB26D'
            Up: '#7EB26D'
          legend:
            percentage: true
            show: true
            sortDesc: true
            values: true
          legendType: Under graph
          span: 3
          type: grafana-piechart-panel
        service_level_row:
          height: 200px
          showTitle: true
        service_row:
          height: 100px
          showTitle: true
      enabled: true

