applications:
  - prometheus
parameters:
  _param:
    prometheus_exporter_jmx_port: 9111
  prometheus:
    exporters:
      jmx:
        packages:
          - jmx-exporter
        services:
          cassandra:
            bind:
              address: 0.0.0.0
              port: ${_param:prometheus_exporter_jmx_port}
