parameters:
  _param:
    alertmanager_notification_pushkin_host: ${_param:haproxy_pushkin_bind_host}
    alertmanager_notification_pushkin_port: ${_param:haproxy_pushkin_bind_port}
  prometheus:
    alertmanager:
      enabled: true
      config:
        route:
          routes:
            pushkin:
              receiver: HTTP-pushkin
              match_re:
                - label: route
                  value: '(.*pushkin.*)'
              continue: true
        receiver:
          HTTP-pushkin:
            enabled: true
            webhook_configs:
              pushkin-vip:
                url: "http://${_param:alertmanager_notification_pushkin_host}:${_param:alertmanager_notification_pushkin_port}/webhook?app=stacklight_alertmanager"
                send_resolved: true
