applications:
  - prometheus
classes:
 - service.prometheus.support
parameters:
  _param:
    prometheus_evaluation_interval: "15s"
    prometheus_region_label: "region1"
    prometheus_scrape_interval: "15s"
    prometheus_storage_retention: "4320h"
    prometheus_server_bind_port: 9090
  prometheus:
    server:
      enabled: true
      is_container: false
      use_grains:
        target: false
        recording: false
        alert: false
      dir:
        config: /etc/prometheus
        data: /var/lib/prometheus/data
      bind:
        port: ${_param:prometheus_server_bind_port}
        address: 0.0.0.0
      storage:
        local:
          retention: ${_param:prometheus_storage_retention}
      alertmanager:
        notification_queue_capacity: 10000
      config:
        global:
          scrape_interval: ${_param:prometheus_scrape_interval}
          scrape_timeout: "15s"
          evaluation_interval: ${_param:prometheus_evaluation_interval}
          external_labels:
            region: ${_param:prometheus_region_label}
