parameters:
  jenkins:
    client:
      job_template:
        docker-build-saas:
          name: docker-image-build-saas-{{subproject}}-{{name}}
          jobs:
            - name: auth
              subproject: core
            - name: application
              subproject: core
            - name: ui
              subproject: frontend
          template:
            discard:
              build:
                keep_num: 25
              artifact:
                keep_num: 25
            type: workflow-scm
            concurrent: false
            scm:
              type: git
              url: "${_param:jenkins_gerrit_url}/oss/jenkins/pipelines"
              credentials: "gerrit"
              script: docker-build-image-pipeline.groovy
            trigger:
              gerrit:
                project:
                  'saas\/{{subproject}}\/{{name}}':
                    compare_type: REG_EXP
                    branches:
                      - master
                skip_vote:
                  - successful
                  - failed
                  - unstable
                  - not_built
                event:
                    patchset:
                        - create:
                            excludeDrafts: false
                            excludeNoCodeChange: false
                    change:
                        - merged
                    comment:
                        - addedContains:
                            commentAddedCommentContains: '^(?s:Patch Set \d+:.*(rebuild)\s*)$'
            param:
                IMAGE_NAME:
                    type: string
                    default: "saas-{{name}}"
                IMAGE_TAGS:
                    type: string
                    default: ""
                CONTEXT_PATH:
                    type: string
                    default: "."
                CREDENTIALS_ID:
                    type: string
                    default: "gerrit"
                DOCKERFILE_PATH:
                    type: string
                    default: "Dockerfile"
                DOCKER_REGISTRY:
                    type: string
                    default: "docker-dev-virtual.docker.mirantis.net"
                PROJECT_NAMESPACE:
                    type: string
                    default: "saas"
