classes:
- docker
parameters:
  _param:
    docker_stack_aptly_public_replicas: 3
    docker_image_aptly:
      # This image is temporary replacement for mirantis/aptly-api because of acquire_by_hash bug
      # https://github.com/smira/aptly/pull/697. We waiting for new release of aptly
      api: breton/aptly-api
      #api: mirantis/aptly-api
      public: mirantis/aptly-public
  docker:
    client:
      stack:
        aptly:
          environment:
            EMAIL_ADDRESS: ${_param:admin_email}
            https_proxy: ${_param:docker_https_proxy}
            http_proxy: ${_param:docker_http_proxy}
          service:
            api:
              deploy:
                restart_policy:
                  condition: any
              image: ${_param:docker_image_aptly:api}
              ports:
                - 18084:8080
              volumes:
                - /srv/volumes/aptly:/var/lib/aptly
            public:
              deploy:
                replicas: ${_param:docker_stack_aptly_public_replicas}
                restart_policy:
                  condition: any
              image: ${_param:docker_image_aptly:public}
              ports:
                - 18085:80
              volumes:
                - /srv/volumes/aptly/public:/var/www/html
