classes:
  - jenkins.client.job.docker.oss.cis-collectors
  - jenkins.client.job.docker.oss.devops-portal
  - jenkins.client.job.docker.oss.hce-codebase
  - jenkins.client.job.docker.oss.hce-docker
  - jenkins.client.job.docker.oss.janitor-monkey-codebase
  - jenkins.client.job.docker.oss.janitor-monkey-docker
  - jenkins.client.job.docker.oss.pushkin-codebase
  - jenkins.client.job.docker.oss.pushkin-codebase-ext
  - jenkins.client.job.docker.oss.pushkin-docker
  - jenkins.client.job.docker.oss.rundeck
  - jenkins.client.job.docker.oss.security-monkey-codebase
  - jenkins.client.job.docker.oss.security-monkey-codebase-openstack
  - jenkins.client.job.docker.oss.security-monkey-docker
