parameters:
  jenkins:
    client:
      job_template:
        docker-build-images:
          name: "docker-build-images-{{name}}"
          jobs:
            - name: aptly
              repo: mk
              build_trigger: ""
            - name: ci
              repo: mk
              build_trigger: "H H(20-23) * * *"
            - name: prometheus
              repo: mcp
              build_trigger: ""
          template:
            discard:
              build:
                keep_num: 25
              artifact:
                keep_num: 25
            type: workflow-scm
            concurrent: true
            scm:
              type: git
              url: "${_param:jenkins_gerrit_url}/{{repo}}/docker-{{name}}"
              credentials: "gerrit"
            trigger:
              gerrit:
                project:
                  "{{repo}}/docker-{{name}}":
                    branches:
                      - master
                event:
                  ref:
                    - updated: {}
              pollscm:
                spec: "{{build_trigger}}"
            param:
              IMAGE_GIT_URL:
                type: string
                default: "${_param:jenkins_gerrit_url}/{{repo}}/docker-{{name}}"
              IMAGE_BRANCH:
                type: string
                default: "master"
              IMAGE_CREDENTIALS_ID:
                type: string
                default: "gerrit"
              IMAGE_TAGS:
                type: string
                default: "latest"
              REGISTRY_URL:
                type: string
                default: ""
              REGISTRY_CREDENTIALS_ID:
                type: string
                default: "mirantis-dockerhub"
              DOCKER_GIT_TAG:
                type: boolean
                default: "true"
              ARTIFACTORY_URL:
                type: string
                default: "docker-dev-virtual.docker.mirantis.net"
                description: "URL to artifactory"
              ARTIFACTORY_NAMESPACE:
                type: string
                default: cicd
                description: "Artifactory namespace (oss, cicd,...)"
              EXTRA_REPO_URL:
                type: string
                default: "${_param:jenkins_aptly_url}"
