parameters:
  jenkins:
    client:
      job_template:
        docker-build-images-opencontrail:
          name: "docker-build-images-opencontrail-{{version}}"
          jobs:
            - version: oc40
              branch: master
            - version: oc41
              branch: master
            - version: oc50
              branch: R5.0
          template:
            discard:
              build:
                keep_num: 25
              artifact:
                keep_num: 25
            type: workflow-scm
            concurrent: true
            scm:
              type: git
              url: "${_param:jenkins_gerrit_url}/mk/docker-opencontrail"
              credentials: "gerrit"
            trigger:
              gerrit:
                project:
                  "mk/docker-opencontrail":
                    branches:
                      - "{{branch}}"
                event:
                  ref:
                    - updated: {}
                  comment:
                    - addedContains:
                        commentAddedCommentContains: '(buildcontainer|test|recheck|verify|)'
              reverse:
                projects:
                  - build-opencontrail-{{version}}-ubuntu-xenial
            param:
              IMAGE_GIT_URL:
                type: string
                default: "${_param:jenkins_gerrit_url}/mk/docker-opencontrail"
              OC_VERSION:
                type: string
                default: "{{version}}"
              IMAGE_CREDENTIALS_ID:
                type: string
                default: "gerrit"
              IMAGE_BRANCH:
                type: string
                default: "{{branch}}"
              APT_KEY:
                type: string
                default: "${_param:jenkins_aptly_url}/public.gpg"
              APT_REPO_URL:
                type: string
                default: "${_param:jenkins_aptly_url}/xenial/ nightly"
              REGISTRY_CREDENTIALS_ID:
                type: string
                default: "dockerhub"
