classes:
- kubernetes.common
parameters:
  kubernetes:
    master:
      enabled: true
      kubelet:
        fail_on_swap: ${_param:kubelet_fail_on_swap}
      container: false
      network:
        genie:
          enabled: ${_param:kubernetes_genie_enabled}
          source: ${_param:kubernetes_genie_source}
          source_hash: ${_param:kubernetes_genie_source_hash}
        calico:
          enabled: ${_param:kubernetes_calico_enabled}
          image: ${_param:kubernetes_calico_image}
          calicoctl_image: ${_param:kubernetes_calico_calicoctl_image}
          cni_image: ${_param:kubernetes_calico_cni_image}
          kube_controllers_image: ${_param:kubernetes_calico_kube_controllers_image}
        opencontrail:
          enabled: ${_param:kubernetes_opencontrail_enabled}
          cni_image: ${_param:kubernetes_contrail_cni_image}
        sriov:
          enabled: ${_param:kubernetes_sriov_enabled}
          source: ${_param:kubernetes_sriov_source}
          source_hash: ${_param:kubernetes_sriov_source_hash}
        flannel:
          enabled: ${_param:kubernetes_flannel_enabled}
