parameters:
  prometheus:
    server:
      target:
        static:
          prometheus:
            endpoint:
             - address: 127.0.0.1
               port: ${prometheus:server:bind:port}
          prometheus_federation:
            honor_labels: true
            metrics_path: '/federate'
            scrape_interval: 15s
            scrape_timeout: 15s
            endpoint:
             - address: ${_param:stacklight_monitor_address}
               port: 15010
