parameters:
  jenkins:
    client:
      job:
        deploy_aws_k8s_kqueen_job:
          name: deploy-aws-k8s-kqueen
          type: workflow-scm
          discard:
            build:
              keep_num: 50
          concurrent: true
          display_name: "Deploy AWS K8S using kqueen"
          scm:
            type: git
            url: "${_param:jenkins_gerrit_url}/mk/mk-pipelines"
            branch: "${_param:jenkins_pipelines_branch}"
            credentials: "gerrit"
            script: deploy-aws-k8s-kqueen-pipeline.groovy
          param:
            # deployments
            STACK_NAME:
              type: string
              description: "AWS stack name - mandatory param, will be used as is"
            STACK_COMPUTE_COUNT:
              type: string
              default: '2'

            STACK_TEMPLATE:
              type: string
              default: "k8s_ha_calico_sm"
            STACK_TEMPLATE_URL:
              type: string
              default: "${_param:jenkins_gerrit_url}/mk/heat-templates"
            STACK_TEMPLATE_CREDENTIALS:
              type: string
              default: "gerrit"
            STACK_TEMPLATE_BRANCH:
              type: string
              default: "master"

            # salt
            SALT_MASTER_CREDENTIALS:
              type: string
              default: "salt-qa-credentials"
            SALT_MASTER_URL:
              type: string
              default: ""
            SALT_OVERRIDES:
              type: text
              default: ""
              description: YAML with overrides for Salt deployment

            # aws api
            AWS_STACK_REGION:
              type: string
              default: "us-west-2"
            AWS_API_CREDENTIALS:
              type: string
              default: "kqueen-aws"
            AWS_SSH_KEY:
              type: string
              default: "jenkins-mk"
            KQUEEN_BUILD_ID:
              type: string
        deploy_heat_k8s_kqueen_job:
          name: deploy-heat-k8s-kqueen
          type: workflow-scm
          discard:
            build:
              keep_num: 50
          concurrent: true
          display_name: "Deploy Heat K8S using kqueen"
          scm:
            type: git
            url: "${_param:jenkins_gerrit_url}/mk/mk-pipelines"
            branch: "${_param:jenkins_pipelines_branch}"
            credentials: "gerrit"
            script: deploy-heat-k8s-kqueen-pipeline.groovy
          param:
            # deployments
            STACK_NAME:
              type: string
              description: "AWS stack name - mandatory param, will be used as is"
            STACK_COMPUTE_COUNT:
              type: string
              default: '2'

            STACK_TEMPLATE:
              type: string
              default: "k8s_ha_calico"
            STACK_TEMPLATE_URL:
              type: string
              default: "${_param:jenkins_gerrit_url}/mk/heat-templates"
            STACK_TEMPLATE_CREDENTIALS:
              type: string
              default: "gerrit"
            STACK_TEMPLATE_BRANCH:
              type: string
              default: "master"

            # salt
            SALT_MASTER_CREDENTIALS:
              type: string
              default: "salt-qa-credentials"
            SALT_MASTER_URL:
              type: string
              default: ""

           # heat
            HEAT_STACK_ENVIRONMENT:
              type: string
              default: "devcloud"
            HEAT_STACK_ZONE:
              type: string
              default: "mcp-mk"
            HEAT_STACK_PUBLIC_NET:
              type: string
              default: "public"

           # openstack api
            OPENSTACK_API_URL:
              type: string
              default: "https://cloud-cz.bud.mirantis.net:5000"
            OPENSTACK_API_CREDENTIALS:
              type: string
              default: "openstack-devcloud-credentials"
            OPENSTACK_API_PROJECT:
              type: string
              default: "mcp-mk"
            KQUEEN_BUILD_ID:
              type: string
