applications:
- prometheus
parameters:
  _param:
    prometheus_evaluation_interval: 15s
    prometheus_region_label: region1
    prometheus_scrape_interval: 15s
    prometheus_server_bind_port: 9090
    prometheus_storage_retention: 4320h
  prometheus:
    server:
      alertmanager:
        notification_queue_capacity: 10000
      bind:
        address: 0.0.0.0
        port: ${_param:prometheus_server_bind_port}
      config:
        global:
          evaluation_interval: ${_param:prometheus_evaluation_interval}
          external_labels:
            region: ${_param:prometheus_region_label}
          scrape_interval: ${_param:prometheus_scrape_interval}
          scrape_timeout: 15s
      dir:
        config: /etc/prometheus
        data: /var/lib/prometheus/data
      enabled: true
      is_container: false
      storage:
        local:
          retention: ${_param:prometheus_storage_retention}
      use_grains:
        alert: false
        recording: false
        target: false
      version: 2

