classes:
- service.kubernetes.logging
- service.kubernetes.monitoring
parameters:
  _param:
    kubernetes_cluster_domain: ${_param:cluster_domain}
  kubernetes:
    common:
      addons:
        dns:
          enabled: true
          replicas: 1
          autoscaler:
            enabled: true
          domain: cluster.local
          server: 10.254.0.10
          dnsmasq:
            cache-size: 1000
            no-resolv:
            server: 127.0.0.1#10053
            log-facility: "-"
        dashboard:
          enabled: True
        heapster_influxdb:
          enabled: False
        helm:
          enabled: False
          tiller_image: gcr.io/kubernetes-helm/tiller:v2.4.2
        netchecker:
          enabled: False
          interval: 60
          namespace: netchecker
          port: 80
          agent_image: mirantis/k8s-netchecker-agent:stable
          server_image: mirantis/k8s-netchecker-server:stable
        calico_policy:
          enabled: False
          image: docker-prod-virtual.docker.mirantis.net/mirantis/projectcalico/calico/kube-controllers:v1.0.4
          namespace: kube-system
        contrail_network_controller:
          enabled: False
          namespace: kube-system
          image: yashulyak/contrail-controller:latest
        coredns:
          enabled: False
          namespace: kube-system
          image: coredns/coredns:latest
          etcd:
            operator_image: quay.io/coreos/etcd-operator:v0.5.2
            version: 3.1.8
            base_image: quay.io/coreos/etcd
        externaldns:
          enabled: False
          namespace: kube-system
          image: mirantis/external-dns:latest
          domain: ${_param:kubernetes_cluster_domain}
          provider: coredns
        virtlet:
          enabled: False
          namespace: kube-system
          image: mirantis/virtlet:v1.0.3
          criproxy_version: v0.10.0
          criproxy_source: md5=52717b1f70f15558ef4bdb0e4d4948da
      cni:
        plugins:
          source: https://github.com/containernetworking/plugins/releases/download/v0.7.1/cni-plugins-amd64-v0.7.1.tgz
          hash: e7e5751d43456f69ea1ed043647e0377
      cloudprovider:
        enabled: False
        provider: openstack
        params:
          region: RegionOne
          domain_name: default
      cluster_domain: ${_param:kubernetes_cluster_domain}
      cluster_name: ${_param:cluster_name}
