applications:
- prometheus
parameters:
  _param:
    prometheus_exporter_libvirt_port: 9177
  prometheus:
    exporters:
      libvirt:
        packages:
        - libvirt-exporter
        services:
          qemu:
            bind:
              address: 0.0.0.0
              port: ${_param:prometheus_exporter_libvirt_port}

