classes:
- prometheus.remote_storage_adapter.container
parameters:
  docker:
    client:
      stack:
        monitoring:
          network:
            monitoring:
              driver: overlay
              driver_opts:
                encrypted: 1
          service:
            remote_storage_adapter:
              networks:
                - monitoring
              deploy:
                replicas: 1
                labels:
                  com.mirantis.monitoring: "remote_storage_adapter"
                restart_policy:
                  condition: any
              labels:
                com.mirantis.monitoring: "remote_storage_adapter"
              image: ${_param:docker_image_remote_storage_adapter}
              ports:
                - 15015:${prometheus:remote_storage_adapter:bind:port}
              environment:
                RSA_BIND_PORT: ${prometheus:remote_storage_adapter:bind:port}
                RSA_BIND_ADDRESS: ${prometheus:remote_storage_adapter:bind:address}
                RSA_INFLUXDB_RETENTION_POLICY: 'lma'
                RSA_INFLUXDB_URL: ${_param:prometheus_influxdb_url}
                RSA_INFLUXDB_DB: ${_param:prometheus_influxdb_db}
                RSA_INFLUXDB_USERNAME: ${_param:prometheus_influxdb_username}
                RSA_INFLUXDB_PASSWORD: ${_param:prometheus_influxdb_password}
