applications:
- docker
classes:
- docker.support
parameters:
  _param:
    docker_garbage_collection_enabled: false
  docker:
    host:
      enabled: true
      experimental: true
      insecure_registries:
      - ${_param:cluster_vip_address}:5000
      - ${_param:cluster_public_host}:5000
      options:
        fixed-cidr-v6: fc00::/7
        ipv6: true
        log-driver: json-file
        log-opts:
          max-size: 50m
        storage-driver: overlay2
      pkgs:
      - docker-ce
      - python-docker
  linux:
    system:
      cron:
        user:
          root:
            enabled: true
      job:
        docker_garbage_collection:
          command: docker system prune -f --filter until=$(date +%s -d "1 week ago")
          enabled: ${_param:docker_garbage_collection_enabled}
          hour: 6
          minute: 0
          user: root

