applications:
- docker
classes:
- docker.support
parameters:
  docker:
    host:
      enabled: true
      experimental: true
      insecure_registries:
      - ${_param:cluster_vip_address}:5000
      - ${_param:cluster_public_host}:5000
      options:
        fixed-cidr-v6: fc00::/7
        ipv6: true
        log-driver: json-file
        log-opts:
          max-size: 50m
        storage-driver: overlay2
      pkgs:
      - docker-ce
      - python-docker

